<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="uiDesign\secretaryDashboard\**" />
		<EmbeddedResource Remove="uiDesign\secretaryDashboard\**" />
		<None Remove="uiDesign\secretaryDashboard\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="backend\database\repository\AdminRepository.cs~RFc081cc.TMP" />
	</ItemGroup>

	<ItemGroup>
	  <COMReference Include="RDPCOMAPILib">
	    <WrapperTool>tlbimp</WrapperTool>
	    <VersionMinor>0</VersionMinor>
	    <VersionMajor>1</VersionMajor>
	    <Guid>cc802d05-ae07-4c15-b496-db9d22aa0a84</Guid>
	    <Lcid>0</Lcid>
	    <Isolated>false</Isolated>
	    <EmbedInteropTypes>true</EmbedInteropTypes>
	  </COMReference>
	  <COMReference Include="AxRDPCOMAPILib">
	    <WrapperTool>aximp</WrapperTool>
	    <VersionMinor>0</VersionMinor>
	    <VersionMajor>1</VersionMajor>
	    <Guid>cc802d05-ae07-4c15-b496-db9d22aa0a84</Guid>
	    <Lcid>0</Lcid>
	    <Isolated>false</Isolated>
	  </COMReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DotnetEnv" Version="3.1.1" />
		<PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
		<PackageReference Include="Krypton.Docking" Version="95.25.4.111" />
		<PackageReference Include="Krypton.Navigator" Version="95.25.4.111" />
		<PackageReference Include="Krypton.Toolkit" Version="95.25.4.111" />
		<PackageReference Include="Krypton.Workspace" Version="95.25.4.111" />
		<PackageReference Include="Mailkit" Version="4.11.0" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.8.0" />
		<PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.Winforms" Version="150.1652.0" />
		<PackageReference Include="Microsoft.ReportViewer.WinForms" Version="10.0.40219.1" />
		<PackageReference Include="Mysql.Data" Version="9.2.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Otp.NET" Version="1.4.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.8.0" />
		<PackageReference Include="Microsoft.Build.Tasks.Git" Version="8.0.0" PrivateAssets="all">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminAccountVerification.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminAccountManagementControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminOfficialsManagementControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminAnnouncementsControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\modals\modals_controls\CreateUsersModalControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\controls\usersDashboardControls.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminUserLogsControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\adminDashboard\controls\AdminDashboardControl.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\modals\modals_controls\AnnouncementsModalControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\modals\modals_controls\BlotterResidentModalCotntrol.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\modals\modals_controls\OfficialsModalControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\secretary_controls\SecretaryAnnouncementsControl.cs" />
		<Compile Update="uiDesign\usersDashboard\secretary_controls\SecretaryOfficialsControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\secretary_controls\SecretaryBlotterControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\secretary_controls\SecretaryApprovalDocumentsControls.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\user_controls\RequestDocumentsControls.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\user_controls\ResidentUserLogsControl.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\modals\modals_controls\RequestDocumentsModalCotntrol.cs">
		  <SubType>UserControl</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\SercretaryPageForm.cs">
		  <SubType>Form</SubType>
		</Compile>
		<Compile Update="uiDesign\usersDashboard\ResidentPageForm.cs">
		  <SubType>Form</SubType>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>